apiVersion: v1
kind: Service
metadata:
  name: {{ template "cicd-gerrit.fullname" . }}-database
  labels:
    app: {{ template "cicd-gerrit.name" . }}
    chart: {{ template "cicd-gerrit.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: {{ .Values.databaseService.ip }}
  type: {{ .Values.databaseService.type }}
  ports:
    - port: {{ .Values.databaseService.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    app: {{ template "cicd-gerrit.name" . }}
    release: {{ .Release.Name }}
