apiVersion: v1
kind: Service
metadata:
  name: {{ template "cicd-gerrit.fullname" . }}-server
  labels:
    app: {{ template "cicd-gerrit.name" . }}
    chart: {{ template "cicd-gerrit.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.serverService.type }}
  clusterIP: {{ .Values.serverService.ip }}
  ports:
    - port: {{ .Values.serverService.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.serverService.sshPort }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    app: {{ template "cicd-gerrit.name" . }}
    release: {{ .Release.Name }}
