apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "cicd-openldap.fullname" . }}
  labels:
    app: {{ template "cicd-openldap.name" . }}
    chart: {{ template "cicd-openldap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "cicd-openldap.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "cicd-openldap.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-server
          image: "{{ .Values.serverImage.repository }}:{{ .Values.serverImage.tag }}"
          imagePullPolicy: {{ .Values.serverImage.pullPolicy }}
          ports:
            - name: ldap
              containerPort: 389
              protocol: TCP
            - name: ldaps
              containerPort: 636
              protocol: TCP
          env:
            - name: HOSTNAME
              value: ldap01.{{ .Values.settings.domain }}
            - name: LDAP_ORGANISATION
              value: {{ .Values.settings.organisation }}
            - name: LDAP_DOMAIN
              value: {{ .Values.settings.domain }}
            - name: LDAP_ADMIN_PASSWORD
              value: {{ .Values.settings.adminPassword }}
            - name: LDAP_CONFIG_PASSWORD
              value: {{ .Values.settings.configPassword }}
            - name: LDAP_TLS
              value: {{ .Values.settings.tls }}
          volumeMounts:
            - mountPath: /var/lib/ldap
              name: ldapDatabase
            - mountPath: /etc/ldap/slapd.d
              name: ldapConfig
          resources:
{{ toYaml .Values.serverResources | indent 12 }}
    {{- with .Values.serverNodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.serverAffinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.serverTolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
        - name: {{ .Chart.Name }}-admin
          image: "{{ .Values.adminImage.repository }}:{{ .Values.adminImage.tag }}"
          imagePullPolicy: {{ .Values.adminImage.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: PHPLDAPADMIN_LDAP_HOSTS
              value: "#PYTHON2BASH:[{'server': [{'server': [{'tls': False}]},{'login': [{'bind_id': 'cn=admin,{{ .Values.settings.domain }}'},{'bind_pass': '{{ .Values.settings.adminPassword }}'}]}]}]"
            - name: PHPLDAPADMIN_HTTPS
              value: "false"
            - name: PHPLDAPADMIN_TRUST_PROXY_SSL
              value: "true"
            - name: PHPLDAPADMIN_SERVER_ADMIN
              value: {{ .Values.settings.adminEmail}}
            - name: PHPLDAPADMIN_THEME
              value: mirantis
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.adminResources | indent 12 }}
    {{- with .Values.adminNodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.adminAffinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.adminTolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: ldapDatabase
        hostPath:
          path: /srv/volumes/openldap/database
      - name: ldapConfig
        hostPath:
          path: /srv/volumes/openldap/config