apiVersion: v1
kind: Service
metadata:
  name: {{ template "cicd-openldap.fullname" . }}
  labels:
    app: {{ template "cicd-openldap.name" . }}
    chart: {{ template "cicd-openldap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.server-service.type }}
  ports:
    - port: {{ .Values.server-service.ldap-public-port }}
      targetPort: ldap
      protocol: TCP
      name: ldap
    - port: {{ .Values.server-service.ldaps-public-port }}
      targetPort: ldaps
      protocol: TCP
      name: ldaps
  selector:
    app: {{ template "cicd-openldap.name" . }}
    release: {{ .Release.Name }}
