apiVersion: v1
kind: Service
metadata:
  name: {{ template "cicd-openldap.fullname" . }}-server
  labels:
    app: {{ template "cicd-openldap.name" . }}
    chart: {{ template "cicd-openldap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.serverService.type }}
  clusterIP: 10.254.34.11
  ports:
    - port: {{ .Values.serverService.ldapPublicPort }}
      targetPort: ldap
      protocol: TCP
      name: ldap
    - port: {{ .Values.serverService.ldapsPublicPort }}
      targetPort: ldaps
      protocol: TCP
      name: ldaps
  selector:
    app: {{ template "cicd-openldap.name" . }}
    release: {{ .Release.Name }}
