apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "cicd-jenkins.fullname" . }}
  labels:
    app: {{ template "cicd-jenkins.name" . }}
    chart: {{ template "cicd-jenkins.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "cicd-jenkins.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "cicd-jenkins.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
            - name: slave-listener
              containerPort: 50000
          env:
            - name: JAVA_OPTS
              value:  {{ .Values.settings.javaOpts }}
            - name: JENKINS_OPTS
              value: {{ .Values.settings.jenkinsOpts }}
            - name: ADMIN_PASSWORD
              value: {{ .Values.settings.admin }}
            - name: ADMIN_USER
              value: {{ .Values.settings.r00tme }}
          livenessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 180
          readinessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 180
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkins-home
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: jenkins-home
        hostPath:
          path: /srv/jenkins
