apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "cicd-jenkins.fullname" . }}
  labels:
    app: {{ template "cicd-jenkins.name" . }}
    chart: {{ template "cicd-jenkins.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "cicd-jenkins.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "cicd-jenkins.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
            - name: slave-listener
              containerPort: 50000
          env:
            - name: JAVA_OPTS
              value: ' -server -XX:+AlwaysPreTouch -Xloggc:/var/jenkins_home/gc-%t.log -XX:NumberOfGCLogFiles=5
                -XX:+UseGCLogFileRotation -XX:GCLogFileSize=20m -XX:+PrintGC -XX:+PrintGCDateStamps
                -XX:+PrintGCDetails -XX:+PrintHeapAtGC -XX:+PrintGCCause -XX:+PrintTenuringDistribution
                -XX:+PrintReferenceGC -XX:+PrintAdaptiveSizePolicy -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent
                -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:+UnlockExperimentalVMOptions
                -XX:G1NewSizePercent=20 -XX:+UnlockDiagnosticVMOptions -XX:G1SummarizeRSetStatsPeriod=1
                -Djenkins.install.runSetupWizard=false -Dhudson.DNSMultiCast.disabled=true -Dhudson.udp=-1
                -Dhudson.footerURL=https://www.mirantis.com '
            - name: JENKINS_OPTS
              value: " --handlerCountMax=40"
            - name: ADMIN_PASSWORD
              value: r00tme
            - name: ADMIN_USER
              value: admin
          livenessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 180
          readinessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 180
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkins-home
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: jenkins-home
        hostPath:
          path: /srv/jenkins
