apiVersion: v1
kind: Service
metadata:
  name: {{ template "cicd-jenkins.fullname" . }}
  labels:
    app: {{ template "cicd-jenkins.name" . }}
    chart: {{ template "cicd-jenkins.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.ip }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: 8080
      name: http
    - port: {{ .Values.service.slavePort }}
      targetPort: 50000
      name: slave-listener
  selector:
    app: {{ template "cicd-jenkins.name" . }}
    release: {{ .Release.Name }}
