replicaCount: 1

serverImage:
  repository: osixia/openldap
  tag: 1.1.8
  pullPolicy: IfNotPresent

serverService:
  type: ClusterIP
  ldapPublicPort: 1389
  ldapsPublicPort: 1636

settings:
  domain: mcp-drivetrain.local
  organisation: mcp-drivetrain
  adminPassword: r00tme
  adminEmail: admin@localhost
  configPassword: r00tme
  tls: "false"

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - chart-example.local
  tls: []

serverResources: {}

serverNodeSelector: {}

serverTolerations: []

serverAffinity: {}

adminImage:
  repository: tcpcloud/phpldapadmin
  tag: 0.6.12
  pullPolicy: IfNotPresent

adminService:
  type: ClusterIP
  adminPublicPort: 18089

adminResources: {}

adminNodeSelector: {}

adminTolerations: []

adminAffinity: {}