replicaCount: 1

server-image:
  repository: osixia/openldap
  tag: 1.1.8
  pullPolicy: IfNotPresent

server-service:
  type: ClusterIP
  ldap-public-port: 1389
  ldaps-public-port: 1636

settings:
  domain: mcp-drivetrain.local
  organisation: mcp-drivetrain
  admin-password: r00tme
  admin-email: admin@localhost
  config-password: r00tme
  tls: "false"

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - chart-example.local
  tls: []

server-resources: {}

server-nodeSelector: {}

server-tolerations: []

server-affinity: {}

admin-image:
  repository: tcpcloud/phpldapadmin
  tag: 0.6.12
  pullPolicy: IfNotPresent

admin-service:
  type: ClusterIP
  admin-public-port: 18089

admin-resources: {}

admin-nodeSelector: {}

admin-tolerations: []

admin-affinity: {}